### ISSUE TITLE
Local Modes

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/odilia#102]
State should be per application, not global.

Most screen readers are expected to be in a dofferent mode based on which app is in active focus.

As Odilia moves forward, we will need *a lot* of tests relared to heuristics of what has happened previously, where the user is  etc.

Ideally, this should be user-configurable via something like the following:

```toml
[modes.default]
rules = [
  { "name": "firefox", mode: "browse+structural-navigation" }
]
```

This is why Orca's code is called directly at every key press, at which point Orca decides whether the key should be consumed or not. If we can at all help it, it would be preferable that Odilia finds a way to fully disable key bindings in the evenr they are no longer valid.

The unfortunate realiy of screen readers is that they are highly dependent on state.
